services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: task_manager
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d/:ro

  server:
    build:
      context: ./server
      dockerfile: dockerfile
    ports:
      - "3002:3000"
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: task_manager
      JWT_SECRET: votre_secret_jwt_super_securise
      ORIGIN: http://localhost:8081
    depends_on:
      - db
    volumes:
      - ./server/uploads:/app/uploads

  client:
    build:
      context: ./client
      dockerfile: dockerfile
      args:
        REACT_APP_API_URL: http://localhost:3002/api
    ports:
      - "8081:80"
    depends_on:
      - server

volumes:
  db_data:
