name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '**' ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: task_manager
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -h 127.0.0.1 -proot"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install server dependencies
        working-directory: server
        run: npm ci

      - name: Build server
        working-directory: server
        run: npm run build

      - name: Run server tests
        working-directory: server
        env:
          NODE_ENV: test
          JWT_SECRET: test_secret
          DB_HOST: 127.0.0.1
          DB_USER: root
          DB_PASSWORD: root
          DB_NAME: task_manager
        run: npm test

      - name: Install client dependencies
        working-directory: client
        run: npm ci

      - name: Build client
        working-directory: client
        run: npm run build

      - name: Run client tests
        working-directory: client
        env:
          CI: true
        run: npm test


